name: Docker build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for Logline Server
      run: docker build server --tag logline-server:$(date +%s)
