# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: E2E tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test_e2e:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install pytest
    - name: Install Logline Agent
      run: |
        python -m pip install ./agent
    - name: Install Logline Server
      run: |
        python -m pip install ./server
    - name: Test with pytest
      run: |
        pytest -v --tb=native -p no:logging e2e_tests
